messages:
  - error: MAJOR_ALARM_CLEARED
    tag: craftd
    values:
      reason: (.*)
    line: 'Major alarm cleared, {reason}'
    model: ietf-alarm
    mapping:
      variables:
        alarms//alarm//additional-text: reason
      static: {}
