# This message is sent when an agent process is terminated
#Jan 24 02:50:31 HOSTNAME ProcMgr-worker: %PROCMGR-6-PROCESS_TERMINATED: 'Bgp' (PID=32058, status=9) has terminated.
messages:
  # 'error' should be unique and vendor agnostic.
  - error: PROCESS_TERMINATED
    tag: PROCMGR-6-PROCESS_TERMINATED
    values:
      agent: ([\w-]+)
      pid|int: (\d+)
    line: ": '{agent}' (PID={pid}, status=9) has terminated."
    model: NO_MODEL
    mapping:
      variables:
        system//processes//process//name: agent
        system//processes//process//pid: pid
      static:
        system//processes//process//state: terminated
