messages:
  - error: INTERFACE_DOWN
    tag: LINK-5-CHANGED
    values:
      interface: (\w+[\.\-\d\/\w+]+)
      changeMode: (\w+)
      status: (\w+)
    line: 'Interface {interface}, changed state to {changeMode} {status}'
    model: openconfig-interfaces
    mapping:
      variables:
        interfaces//interface//{interface}//state//oper_status: status
      static: {}